export const Data = [
    {
        id: 1,
        name: 'Bigarreaux 3Kg',
        price: '9,00€',
        quantity: 100,
        description: 'Bigarreaux 3Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
    {
        id: 2,
        name: 'Bigarreaux 5Kg',
        price: '15,00€',
        quantity: 150,
        description: 'Bigarreaux 5Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
    {
        id: 3,
        name: 'Bigarreaux 10Kg',
        price: '25,00€',
        quantity: 200,
        description: 'Bigarreaux 10Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
    {
        id: 4,
        name: 'Ferrovia 3Kg',
        price: '9,00€',
        quantity: 220,
        description: 'Ferrovia 3Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
    {
        id: 5,
        name: 'Ferrovia 5Kg',
        price: '15,00€',
        quantity: 250,
        description: 'Ferrovia 5Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
    {
        id: 6,
        name: 'Ferrovia 10Kg',
        price: '25,00€',
        quantity: 300,
        description: 'Ferrovia 10Kg',
        category: 'Food',
        subcategory: 'Fruits',
        type: 'Fruit',
        unit: 'Kg',
    },
];
